version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - "node.hostname==swarm-master"
    # Uzzināt master node name `docker node ls`, lai dockeris nemaina lokāciju.
    #       - "node.role==manager" atradīsies tikai uz manager node. Ja vairāki manager, tad nederēs.
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow

  redis:
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - "node.hostname==swarm-master"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    depends_on:
      - postgres
    networks:
      - airflow

  registry:
    image: registry:2
    ports:
      - 5000:5000
    deploy:
      placement:
        constraints:
          - "node.hostname==swarm-master"
    volumes:
      - registry:/var/lib/registry
    restart: always
    networks:
      - airflow

networks:
  airflow:
    external: true

volumes:
  postgres:
  registry: