version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres:/var/lib/postgresql/data
    # deploy:
    #   placement:
    #     constraints:
    #       - node.hostname == <target_node_name>
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow

  redis:
    image: redis:latest
    # deploy:
    #   placement:
    #     constraints:
    #       - node.hostname == <target_node_name>
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    depends_on:
      - postgres
    networks:
      - airflow

  registry:
    image: registry:2
    # deploy:
    #   placement:
    #     constraints:
    #       - node.hostname == <target_node_name>
    # Uzzināt master node name, lai var docker nemaina lokāciju... Komanda: docker node ls
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
    restart: always
    networks:
      - airflow

networks:
  airflow:
    external: true

volumes:
  postgres:
  registry: